global using AutoMapper;
global using FluentValidation;
global using Formation.Application.Common.Model;
global using Formation.Application.Repositories;
global using Formation.Application.Repositories.Common;
global using Formation.Domain.Entities;
global using Formation.Domain.Entities.Common;
global using Formation.Domain.Enums;
global using MediatR;
