global using System.Linq;
global using Application.Validation.Tests.Drivers;
global using Application.Validation.Tests.Extentions;
global using FluentAssertions;
global using Formation.Application.Authors.Commands.CreateAuthor;
global using Formation.Application.Authors.Queries.GetAllAuthors;
global using Formation.Application.Books.Commands.CreateBook;
global using Formation.Application.Repositories;
global using Formation.Domain.Entities;
global using MediatR;
global using Microsoft.Extensions.DependencyInjection;
global using Moq;
global using NUnit.Framework;
global using TechTalk.SpecFlow;
global using TechTalk.SpecFlow.Assist;
global using static Application.Validation.Tests.Testing;
